import React from 'react';

export const RecomendationContext = React.createContext({
  currentStep: 1,
  categorySelected: '',
  subCategorySelected: '',
  colorSelected: '',
  categories: [],
  subcategories: [],
  colors: [],
  isLoading: false,
  products: [],
  setSubCategorySelected: () => {},
  setCategorie: () => {},
  setSubCategories: () => {},
  setColors: () => {},
  updateStep: () => {},
  changeStep: () => {},
  getSubCategories: () => {},
  getColors: () => {},
  handleGoBack: () => {},
  setProduct: () => {},
  getProduct: () => {},
  setCurrentStep: () => {},
  startNewRecomendation: () => {},
});
